### ISSUE TITLE
Does not work when an object property is a Date

### ISSUE THREAD

**Issue by joelkoz** [odynvolk/omit-deep-lodash#3]
If an object property is a javascript Date object and it is NOT to be omitted, the value is transformed to an empty object ({}) vs. retaining its date value.

Looking deeper, all non-omitted properties that are objects lose their prototype chains and thus their true type. This implementation is thus best used for simple JSON type objects like data objects and not typed object graphs where members have objects with constructors.

**Comment by odynvolk** [comment]
You sir are correct. I've myself have only used this for straight JSON objects. I've added your finding to the readme.

Thanks for the feedback!
