### ISSUE TITLE
omitDeep changes timestamp strings to objects

### ISSUE THREAD

**Issue by tahv0** [odynvolk/omit-deep-lodash#6]
If I have eg. created_at or updated_at keys with timestap values in string format, omitDeep changes values to empty objects.
Start object before omitting:
```
        {"created_at": "2017-08-24T13:04:58.558Z",
        "updated_at": "2017-08-24T13:04:58.525Z"}
```
After omitDeep (and without even omitting these keys):
```
        {"created_at": {},
        "updated_at": {}}
```

**Comment by odynvolk** [comment]
Hi there!

Thanks for the bug report. I do have problems recreating it though. I added 3 tests based on your description, but they pass. I also tried with different Node versions etc but that worked too.

Could you do a pull and see if all tests (with the new ones) pass on your side?

Cheers!
